### ISSUE TITLE
Shouldn't wallabyTest.ts be named wallabyTest.js?

### ISSUE THREAD

**Issue by victornoel** [wallabyjs/ngCliWebpackSample#11]
Hi,

I don't get how it works with `wallabyWebpack` if the later is looking for src/wallabyTest.js as an entry point?

**Comment by ArtemGovorov** [comment]
Hi,

As [specified in the docs section](https://wallabyjs.com/docs/integration/webpack.html#entry-patterns): *"you need to specify entry patterns with `.js` extension because the compiler is executed before the webpack postprocessor and it renames compiled files by default."*, so by the time wallaby-webpack runs, `src/wallabyTest.ts` becomes `src/wallabyTest.js`.

**Comment by victornoel** [comment]
ok, thanks :)
