### ISSUE TITLE
wallaby.js config error?

### ISSUE THREAD

**Issue by gh0st** [wallabyjs/ngCliWebpackSample#37]
Should the `wallabyWebpack({ entryPatterns })` be `src/wallabyTest.ts` and not `src/wallabyTest.js` inside the `wallaby.js`?

**Comment by ArtemGovorov** [comment]
The `.js` extensiosn in this instance is actually correct, the reason is [described in the docs](https://wallabyjs.com/docs/integration/webpack.html#entry-patterns): 

`
Please note, that if you are using default TypeScript compiler with entry patterns, you need to specify entry patterns with .js extension because the compiler is executed before the webpack postprocessor and it renames compiled files by default.
`
